// <auto-generated />
using System;
using AngularMultiLanguage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularMultiLanguage.Migrations
{
    [DbContext(typeof(MutltiLanDBContext))]
    partial class MutltiLanDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularMultiLanguage.Entities.TblAppLangMaster", b =>
                {
                    b.Property<string>("LangCode")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LangName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("LangCode");

                    b.ToTable("TblAppLangMasters");
                });

            modelBuilder.Entity("AngularMultiLanguage.Entities.TblCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TblCountries");
                });

            modelBuilder.Entity("AngularMultiLanguage.Entities.TblCountryTran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("LangCode");

                    b.ToTable("TblCountryTrans");
                });

            modelBuilder.Entity("AngularMultiLanguage.Entities.TblCountryTran", b =>
                {
                    b.HasOne("AngularMultiLanguage.Entities.TblCountry", "TblCountry")
                        .WithMany("TblCountryTrans")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AngularMultiLanguage.Entities.TblAppLangMaster", "TblAppLangMaster")
                        .WithMany()
                        .HasForeignKey("LangCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblAppLangMaster");

                    b.Navigation("TblCountry");
                });

            modelBuilder.Entity("AngularMultiLanguage.Entities.TblCountry", b =>
                {
                    b.Navigation("TblCountryTrans");
                });
#pragma warning restore 612, 618
        }
    }
}
